# server configuration
server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    key-store: classpath:keystore.p12
    key-password: wangqing
    key-store-type: PKCS12
    key-alias: tomcat

# sql configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chileme?useUnicode=true&characterEncoding=UTF8&usrSSL=false&serverTimezone=UTC
    username: root
    password: 77891
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true   # org.hibernate.SQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect # Hibernate方言


# log configuration
#logging:
#  level:
#    root: debug